In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("emp.csv")

In [3]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10

In [4]:
# specify which columns to read
df = pd.read_csv("emp.csv",usecols=["eno","ename","salary"])

In [19]:
# create a primary (eno)
df = pd.read_csv("emp.csv",usecols=["eno","ename","salary"],index_col="eno")

In [20]:
df = pd.read_csv("emp.csv")

In [21]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10

In [23]:
# Get specific rows
df.loc[[2,3,8]]

   eno   ename  salary  deptno         doj
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
8    9   Naman    4000      30  2020-01-20

In [25]:
# Get specific rows
df.iloc[[2,3,8]]

   eno   ename  salary  deptno         doj
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
8    9   Naman    4000      30  2020-01-20

In [26]:
# Get specific rows
df[['eno','ename']].iloc[[2,3,8]]

   eno   ename
2    8   Sagar
3    4  Thomas
8    9   Naman

In [29]:
# Get specific rows and columns in range
# SQL : select eno,ename from emp where rownum between 2 and 8
df[['eno','ename']].iloc[2:8:2]

   eno   ename
2    8   Sagar
4    5    Jade
6    7  Robert

In [30]:
df.dtypes

eno        int64
ename     object
salary     int64
deptno     int64
doj       object
dtype: object

In [34]:
#Specify data types of columns
df = pd.read_csv("emp.csv",dtype={"salary":float,"deptno":float})

In [35]:
df.dtypes

eno         int64
ename      object
salary    float64
deptno    float64
doj        object
dtype: object

In [36]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber  1000.0    10.0  2018-05-14
1    2    Amar  1000.0    10.0  2017-03-22
2    8   Sagar  1000.0    20.0  2020-11-30
3    4  Thomas  1000.0    10.0  2019-08-18
4    5    Jade  2000.0    10.0  2021-02-10

In [38]:
df = pd.read_csv("netflix_dataset.csv")

In [40]:
df.count()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
listed_in       8807
description     8807
dtype: int64

In [53]:
# Read the data in chunk
for chunk in pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000):
    print(chunk.head(10))

  show_id                             title
0      s1              Dick Johnson Is Dead
1      s2                     Blood & Water
2      s3                         Ganglands
3      s4             Jailbirds New Orleans
4      s5                      Kota Factory
5      s6                     Midnight Mass
6      s7  My Little Pony: A New Generation
7      s8                           Sankofa
8      s9     The Great British Baking Show
9     s10                      The Starling
     show_id                               title
1000   s1001                            Wild Dog
1001   s1002                            Oloibiri
1002   s1003                        Tell Me When
1003   s1004                                Zero
1004   s1005                  Izzy's Koala World
1005   s1006  Keymon and Nani in Space Adventure
1006   s1007            Motu Patlu Dino Invasion
1007   s1008         Motu Patlu in Octupus World
1008   s1009             Motu Patlu VS Robo Kids
1009   s1010     Rudra: Secret of the Black Moon
     show_id                      title
2000   s2001  Michael McIntyre: Showman
2001   s2002      Raising Victor Vargas
2002   s2003            Taco Chronicles
2003   s2004               The Smurfs 2
2004   s2005        Wish Upon a Unicorn
2005   s2006          Lara and the Beat
2006   s2007                      Buddi
2007   s2008                 Dad Wanted
2008   s2009            Family Business
2009   s2010                Girlfriends
     show_id                                        title
3000   s3001         Pandemic: How to Prevent an Outbreak
3001   s3002                            Playing with Fire
3002   s3003                                       Whisky
3003   s3004              Fortune Feimster: Sweet & Salty
3004   s3005                          KD (A) Karuppudurai
3005   s3006  DreamWorks How to Train Your Dragon Legends
3006   s3007                        Motichoor Chaknachoor
3007   s3008                            WHAT DID JACK DO?
3008   s3009                               The Bling Ring
3009   s3010                            A Fall from Grace
     show_id                              title
4000   s4001                       5 Flights Up
4001   s4002                         Green Door
4002   s4003                         Bombairiya
4003   s4004                           Burn Out
4004   s4005       Edoardo Ferrario: Temi Caldi
4005   s4006                               Girl
4006   s4007                If I Hadn't Met You
4007   s4008   Jeff Dunham: Arguing with Myself
4008   s4009      Jeff Dunham: Controlled Chaos
4009   s4010  Jeff Dunham: Minding the Monsters
     show_id                              title
5000   s5001                         Flint Town
5001   s5002  Malena Pichot: Estupidez compleja
5002   s5003   Natalia Valdebenito: El especial
5003   s5004                           Ravenous
5004   s5005                         21 Thunder
5005   s5006       Adel Karam: Live from Beirut
5006   s5007                       Battle Drone
5007   s5008                             Dil Se
5008   s5009                               Guru
5009   s5010                           Judwaa 2
     show_id                         title
6000   s6001                     21 & Over
6001   s6002  21 Sarfarosh: Saragarhi 1897
6002   s6003          2307: Winter's Dream
6003   s6004              24 Hours to Live
6004   s6005   27, el club de los malditos
6005   s6006             27: Gone Too Soon
6006   s6007                       28 Days
6007   s6008                   3 Deewarein
6008   s6009                 3 Generations
6009   s6010                    3 Heroines
     show_id                                  title
7000   s7001                   Hostage to the Devil
7001   s7002                               Hostages
7002   s7003                               Hostiles
7003   s7004                                Hot Bot
7004   s7005                           Hot Property
7005   s7006                                Hot Rod
7006   s7007                      Hotel Beau Séjour
7007   s7008                          Hotel Pacific
7008   s7009  Hotel Transylvania 3: Summer Vacation
7009   s7010         House at the End of the Street
     show_id                     title
8000   s8001              She Did That
8001   s8002                   Shelter
8002   s8003                  Sherlock
8003   s8004           Sherlock Holmes
8004   s8005                     Shiva
8005   s8006       Shopkins: Chef Club
8006   s8007            Shopkins: Wild
8007   s8008  Shopkins: World Vacation
8008   s8009                   Shorgul
8009   s8010             Short Term 12

In [54]:
# Read the data in chunk using iterator
iterator =  pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000,iterator=True)
for chunk in iterator:
    print(chunk)

    show_id                                  title
0        s1                   Dick Johnson Is Dead
1        s2                          Blood & Water
2        s3                              Ganglands
3        s4                  Jailbirds New Orleans
4        s5                           Kota Factory
..      ...                                    ...
995    s996                              Vizontele
996    s997                             HOMUNCULUS
997    s998  Life in Color with David Attenborough
998    s999                   Searching For Sheela
999   s1000                               Stowaway

[1000 rows x 2 columns]
     show_id                               title
1000   s1001                            Wild Dog
1001   s1002                            Oloibiri
1002   s1003                        Tell Me When
1003   s1004                                Zero
1004   s1005                  Izzy's Koala World
...      ...                                 ...
1995   s1996              The Devil All The Time
1996   s1997                       The Paramedic
1997   s1998                            The Take
1998   s1999                    Call the Midwife
1999   s2000  Hope Frozen: A Quest to Live Twice

[1000 rows x 2 columns]
     show_id                                           title
2000   s2001                       Michael McIntyre: Showman
2001   s2002                           Raising Victor Vargas
2002   s2003                                 Taco Chronicles
2003   s2004                                    The Smurfs 2
2004   s2005                             Wish Upon a Unicorn
...      ...                                             ...
2995   s2996                                   Airplane Mode
2996   s2997  Alex Fernández: The Best Comedian in the World
2997   s2998                                 October Faction
2998   s2999             ​SAINT SEIYA: Knights of the Zodiac
2999   s3000                                 The Ghost Bride

[1000 rows x 2 columns]
     show_id                                 title
3000   s3001  Pandemic: How to Prevent an Outbreak
3001   s3002                     Playing with Fire
3002   s3003                                Whisky
3003   s3004       Fortune Feimster: Sweet & Salty
3004   s3005                   KD (A) Karuppudurai
...      ...                                   ...
3995   s3996    Alexis Viera: A Story of Surviving
3996   s3997                            February 9
3997   s3998                                 Imago
3998   s3999                  My Husband Won't Fit
3999   s4000                   Amy Schumer Growing

[1000 rows x 2 columns]
     show_id                         title
4000   s4001                  5 Flights Up
4001   s4002                    Green Door
4002   s4003                    Bombairiya
4003   s4004                      Burn Out
4004   s4005  Edoardo Ferrario: Temi Caldi
...      ...                           ...
4995   s4996                  Ladies First
4996   s4997                   Bullet Head
4997   s4998                   Borderliner
4998   s4999   Gad Elmaleh: American Dream
4999   s5000              Expedition China

[1000 rows x 2 columns]
     show_id                              title
5000   s5001                         Flint Town
5001   s5002  Malena Pichot: Estupidez compleja
5002   s5003   Natalia Valdebenito: El especial
5003   s5004                           Ravenous
5004   s5005                         21 Thunder
...      ...                                ...
5995   s5996                      1st Summoning
5996   s5997               20 Feet From Stardom
5997   s5998                 2015 Dream Concert
5998   s5999                2036 Origin Unknown
5999   s6000                 20th Century Women

[1000 rows x 2 columns]
     show_id                         title
6000   s6001                     21 & Over
6001   s6002  21 Sarfarosh: Saragarhi 1897
6002   s6003          2307: Winter's Dream
6003   s6004              24 Hours to Live
6004   s6005   27, el club de los malditos
...      ...                           ...
6995   s6996        Hope: One in a Billion
6996   s6997                      Hormones
6997   s6998                         Horns
6998   s6999                  Horror Homes
6999   s7000                  Horror Story

[1000 rows x 2 columns]
     show_id                                             title
7000   s7001                              Hostage to the Devil
7001   s7002                                          Hostages
7002   s7003                                          Hostiles
7003   s7004                                           Hot Bot
7004   s7005                                      Hot Property
...      ...                                               ...
7995   s7996                                          Shanghai
7996   s7997                                          Shararat
7997   s7998                                     Shark Busters
7998   s7999                                       Shark Night
7999   s8000  Shaurya: It Takes Courage to Make Right... Right

[1000 rows x 2 columns]
     show_id            title
8000   s8001     She Did That
8001   s8002          Shelter
8002   s8003         Sherlock
8003   s8004  Sherlock Holmes
8004   s8005            Shiva
...      ...              ...
8802   s8803           Zodiac
8803   s8804      Zombie Dumb
8804   s8805       Zombieland
8805   s8806             Zoom
8806   s8807           Zubaan

[807 rows x 2 columns]

In [59]:
# Read the rows from 10 to 20th rows
df = pd.read_csv("emp.csv")
# way 1
df.iloc[9:20]

    eno   ename  salary  deptno         doj
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29

In [67]:
# Create a dataframe with rows 10 to 20
df = pd.read_csv("emp.csv",skiprows=10,nrows=11,header=None,names=['empid','ename','sal','deptno','hiringDate'])

In [68]:
df

    empid   ename    sal  deptno  hiringDate
0       1   Vikas   1000      30  2017-10-03
1      11  Dennis  41000      30  2024-01-05
2      12   Karan   2200      20  2018-06-16
3      13  Simran   1500      10  2019-12-19
4      14    Amit   2000      30  2022-04-09
5      15    Neha   1700      20  2021-07-22
6      16   Rahul   1200      10  2016-03-28
7      17   Divya   3000      30  2015-11-11
8      18  Rakesh   1800      10  2020-09-04
9      19  Monica   2500      20  2023-08-07
10     20    John   2300      30  2018-10-29

In [69]:
df = pd.read_csv("emp.csv",header=0)

In [71]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10

In [75]:
df = pd.read_csv("emp.csv",header=None)

In [76]:
df.head()

     0       1       2       3           4
0  eno   ename  salary  deptno         doj
1   10   Amber    1000      10  2018-05-14
2    2    Amar    1000      10  2017-03-22
3    8   Sagar    1000      20  2020-11-30
4    4  Thomas    1000      10  2019-08-18

In [80]:
df = pd.read_csv("emp.csv",parse_dates=["doj"])

In [81]:
df.dtypes

eno                int64
ename             object
salary             int64
deptno             int64
doj       datetime64[ns]
dtype: object

In [85]:
df['doj'].head()

0   2018-05-14
1   2017-03-22
2   2020-11-30
3   2019-08-18
4   2021-02-10
Name: doj, dtype: datetime64[ns]

In [88]:
df['doj'].dt.year.head()

0    2018
1    2017
2    2020
3    2019
4    2021
Name: doj, dtype: int32

In [89]:
df['doj'].dt.month.head()

0     5
1     3
2    11
3     8
4     2
Name: doj, dtype: int32

In [99]:
# Filtering ( where clause in SQL)
# Get me all the employees who nbelongs to deptno = 30 and salary > 3000
df = pd.read_csv("emp.csv")
filter1  = df['deptno'] == 30
filter2  = df['salary'] > 3000
df[filter1&filter2]

    eno   ename  salary  deptno         doj
8     9   Naman    4000      30  2020-01-20
10   11  Dennis   41000      30  2024-01-05

In [100]:
# Get me all the employees who nbelongs to deptno = 30 or salary > 3000
df = pd.read_csv("emp.csv")
filter1  = df['deptno'] == 30
filter2  = df['salary'] > 3000
df[filter1|filter2]

    eno   ename  salary  deptno         doj
7     3    Nick    1000      30  2015-09-15
8     9   Naman    4000      30  2020-01-20
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      30  2024-01-05
13   14    Amit    2000      30  2022-04-09
16   17   Divya    3000      30  2015-11-11
19   20    John    2300      30  2018-10-29
22   23   Anita    1500      30  2019-05-21
26   27  Kavita    1400      30  2019-01-06
32   33   Nidhi    2400      30  2016-05-12
35   36    Ritu    3200      20  2023-05-01
36   37   Kunal    2800      30  2015-08-22
39   40    Yash    2500      30  2020-07-19
42   43   Geeta    2100      30  2017-11-14
45   46   Manoj    1700      30  2019-07-24

In [102]:
df.head(10)

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10
5    6   Smith    1000      10  2016-12-01
6    7  Robert    3000      20  2023-06-25
7    3    Nick    1000      30  2015-09-15
8    9   Naman    4000      30  2020-01-20
9    1   Vikas    1000      30  2017-10-03

In [103]:
flag = df['deptno'] == 10

In [105]:
df[flag]

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  2018-05-14
1     2    Amar    1000      10  2017-03-22
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-02-10
5     6   Smith    1000      10  2016-12-01
12   13  Simran    1500      10  2019-12-19
15   16   Rahul    1200      10  2016-03-28
17   18  Rakesh    1800      10  2020-09-04
20   21   Sneha    2700      10  2022-12-14
23   24   Vinod    1800      10  2016-07-30
25   26   Harsh    1600      10  2021-09-25
27   28   Mohan    1300      10  2015-04-17
29   30  Suresh    1100      10  2018-09-09
31   32    Ajay    2100      10  2020-06-26
34   35   Seema    3000      10  2021-10-15
37   38    Alok    2700      10  2019-03-02
41   42   Tarun    2200      10  2021-01-09
43   44   Ashok    1900      10  2016-06-08

In [109]:
# Sorting , sort by value and sort by index
# sort by value using single column in ascending order
df.sort_values(by='salary',ascending=True).head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
5    6   Smith    1000      10  2016-12-01

In [111]:
# Sorting , sort by value and sort by index
# sort by value using single column in ascending order
df.sort_values(by='salary',ascending=False).head()

    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
8     9   Naman    4000      30  2020-01-20
35   36    Ritu    3200      20  2023-05-01
6     7  Robert    3000      20  2023-06-25
16   17   Divya    3000      30  2015-11-11

In [117]:
# sort the data by deptno in ascending order and salary in decsending
df1 = df.sort_values(by=['deptno','salary'],ascending=[True,False])

In [119]:
df1.head()

    eno  ename  salary  deptno         doj
34   35  Seema    3000      10  2021-10-15
20   21  Sneha    2700      10  2022-12-14
37   38   Alok    2700      10  2019-03-02
41   42  Tarun    2200      10  2021-01-09
31   32   Ajay    2100      10  2020-06-26

In [121]:
# inplace changes
df.sort_values(by=['deptno','salary'],ascending=[True,False],inplace=True)

In [122]:
df

    eno    ename  salary  deptno         doj
34   35    Seema    3000      10  2021-10-15
20   21    Sneha    2700      10  2022-12-14
37   38     Alok    2700      10  2019-03-02
41   42    Tarun    2200      10  2021-01-09
31   32     Ajay    2100      10  2020-06-26
4     5     Jade    2000      10  2021-02-10
43   44    Ashok    1900      10  2016-06-08
17   18   Rakesh    1800      10  2020-09-04
23   24    Vinod    1800      10  2016-07-30
25   26    Harsh    1600      10  2021-09-25
12   13   Simran    1500      10  2019-12-19
27   28    Mohan    1300      10  2015-04-17
15   16    Rahul    1200      10  2016-03-28
29   30   Suresh    1100      10  2018-09-09
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
3     4   Thomas    1000      10  2019-08-18
5     6    Smith    1000      10  2016-12-01
35   36     Ritu    3200      20  2023-05-01
6     7   Robert    3000      20  2023-06-25
38   39   Poonam    2600      20  2022-02-05
18   19   Monica    2500      20  2023-08-07
40   41     Nina    2300      20  2018-12-28
11   12    Karan    2200      20  2018-06-16
24   25    Meena    2000      20  2020-03-13
33   34    Vivek    2000      20  2017-07-31
30   31     Rani    1900      20  2022-11-03
44   45  Sanjana    1800      20  2023-03-17
14   15     Neha    1700      20  2021-07-22
46   47    Payal    1600      20  2015-10-10
28   29    Priya    1200      20  2023-02-11
2     8    Sagar    1000      20  2020-11-30
21   22    David    1000      20  2017-02-17
10   11   Dennis   41000      30  2024-01-05
8     9    Naman    4000      30  2020-01-20
16   17    Divya    3000      30  2015-11-11
36   37    Kunal    2800      30  2015-08-22
39   40     Yash    2500      30  2020-07-19
32   33    Nidhi    2400      30  2016-05-12
19   20     John    2300      30  2018-10-29
42   43    Geeta    2100      30  2017-11-14
13   14     Amit    2000      30  2022-04-09
45   46    Manoj    1700      30  2019-07-24
22   23    Anita    1500      30  2019-05-21
26   27   Kavita    1400      30  2019-01-06
7     3     Nick    1000      30  2015-09-15
9     1    Vikas    1000      30  2017-10-03

In [124]:
df.sort_index()

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

# Doubt session

In [129]:
# Read the data in chunk
for chunk in pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000):
    print(chunk[chunk['show_id'] =='s996'])

    show_id      title
995    s996  Vizontele
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []

In [137]:
# Read the data in chunk
for chunk in pd.read_csv("netflix_dataset.csv",usecols=["show_id","title"],chunksize=1000):
    fil = chunk['title'] == 'Blood & Water'
    print(chunk[fil])

  show_id          title
1      s2  Blood & Water
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []
Empty DataFrame
Columns: [show_id, title]
Index: []

In [138]:
#Specify data types of columns
df = pd.read_csv("emp.csv",dtype={"salary":float,"deptno":float,"doj":datetime})

NameError: name 'datetime' is not defined

In [139]:
df

    eno    ename  salary  deptno         doj
34   35    Seema    3000      10  2021-10-15
20   21    Sneha    2700      10  2022-12-14
37   38     Alok    2700      10  2019-03-02
41   42    Tarun    2200      10  2021-01-09
31   32     Ajay    2100      10  2020-06-26
4     5     Jade    2000      10  2021-02-10
43   44    Ashok    1900      10  2016-06-08
17   18   Rakesh    1800      10  2020-09-04
23   24    Vinod    1800      10  2016-07-30
25   26    Harsh    1600      10  2021-09-25
12   13   Simran    1500      10  2019-12-19
27   28    Mohan    1300      10  2015-04-17
15   16    Rahul    1200      10  2016-03-28
29   30   Suresh    1100      10  2018-09-09
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
3     4   Thomas    1000      10  2019-08-18
5     6    Smith    1000      10  2016-12-01
35   36     Ritu    3200      20  2023-05-01
6     7   Robert    3000      20  2023-06-25
38   39   Poonam    2600      20  2022-02-05
18   19   Monica    2500      20  2023-08-07
40   41     Nina    2300      20  2018-12-28
11   12    Karan    2200      20  2018-06-16
24   25    Meena    2000      20  2020-03-13
33   34    Vivek    2000      20  2017-07-31
30   31     Rani    1900      20  2022-11-03
44   45  Sanjana    1800      20  2023-03-17
14   15     Neha    1700      20  2021-07-22
46   47    Payal    1600      20  2015-10-10
28   29    Priya    1200      20  2023-02-11
2     8    Sagar    1000      20  2020-11-30
21   22    David    1000      20  2017-02-17
10   11   Dennis   41000      30  2024-01-05
8     9    Naman    4000      30  2020-01-20
16   17    Divya    3000      30  2015-11-11
36   37    Kunal    2800      30  2015-08-22
39   40     Yash    2500      30  2020-07-19
32   33    Nidhi    2400      30  2016-05-12
19   20     John    2300      30  2018-10-29
42   43    Geeta    2100      30  2017-11-14
13   14     Amit    2000      30  2022-04-09
45   46    Manoj    1700      30  2019-07-24
22   23    Anita    1500      30  2019-05-21
26   27   Kavita    1400      30  2019-01-06
7     3     Nick    1000      30  2015-09-15
9     1    Vikas    1000      30  2017-10-03

In [149]:
df = pd.read_csv("emp.csv",index_col="eno")
df.head()

      ename  salary  deptno         doj
eno
10    Amber    1000      10  2018-05-14
2      Amar    1000      10  2017-03-22
8     Sagar    1000      20  2020-11-30
4    Thomas    1000      10  2019-08-18
5      Jade    2000      10  2021-02-10

In [159]:
df.iloc[[0,5]]

     ename  salary  deptno         doj
eno
10   Amber    1000      10  2018-05-14
6    Smith    1000      10  2016-12-01

In [157]:
df.loc[[4,5]]

      ename  salary  deptno         doj
eno
4    Thomas    1000      10  2019-08-18
5      Jade    2000      10  2021-02-10

In [164]:
import datetime

df = pd.read_csv(
    "emp.csv",
    dtype={
        "salary": float,
        "deptno": float,
        "doj": datetime.datetime
    }
)

TypeError: dtype '<class 'datetime.datetime'>' not understood