In [3]:
import pandas as pd
from sqlalchemy import create_engine
import cx_Oracle
mysql_conn = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/aug_2026")

In [2]:
# Create a connection string
mysql_conn = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/aug_2026")

In [3]:
mysql_conn

Engine(mysql+pymysql://root:***@localhost:3308/aug_2026)

In [4]:
# Read the data from mysql database and store in dataframe
df_target = pd.read_sql("select * from product",mysql_conn)

In [5]:
df_target.head()

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
3,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE
4,1005,27 Inch Monitor,Electronics,21999.0,25,VisionTech,ACTIVE

In [11]:
df_source = pd.read_csv("data/product.csv")

In [12]:
df_source.head()

,product_id,product_name,category,price,quantity,supplier,product_status
0,1030,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
1,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
2,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
3,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
4,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE

In [20]:
fil = ~df_source['product_id'].isin(df_target['product_id'])

In [21]:
fil

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22     True
Name: product_id, dtype: bool

In [22]:
df_source[fil]

,product_id,product_name,category,price,quantity,supplier,product_status
0,1030,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
21,1040,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE
22,1050,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE

In [23]:
# Q1. Assume my source : oracle db and target : mysql db , identify which product_id's are not loaded in 
#target but available in source

In [67]:
# Create a connection string
mysql_tgt_conn = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/aug_2026")
oracle_src_conn = create_engine("oracle+cx_oracle://system:admin@localhost:1521/xe")

In [29]:
df_source = pd.read_sql("select * from product",oracle_src_conn)

In [30]:
df_source.head()

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
3,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE
4,1005,27 Inch Monitor,Electronics,21999.0,25,VisionTech,ACTIVE

In [ ]:
df_target = pd.read_sql("select * from product",mysql_tgt_conn)

In [31]:
df_target.head()

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
3,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE
4,1005,27 Inch Monitor,Electronics,21999.0,25,VisionTech,ACTIVE

In [35]:
# Check if source is having any extra product_id's than target
# SQL : select product_id from source 
#       minus
#       select product_id from target

fil = ~df_source['product_id'].isin(df_target['product_id'])
df_source[fil]

Empty DataFrame
Columns: [product_id, product_name, category, price, quantity, supplier, product_status]
Index: []

In [38]:
# Check if target is having any extra product_id's than source
# SQL : select product_id from target 
#       minus
#       select product_id from source

fil = ~df_target['product_id'].isin(df_source['product_id'])
df_target[fil]

Empty DataFrame
Columns: [product_id, product_name, category, price, quantity, supplier, product_status]
Index: []

In [64]:
# Q2. Assume my source : csv file and target : mysql db , identify the extra records by comparing all the columns
df_source = pd.read_csv("data/product.csv")
df_target = pd.read_sql("select * from product",mysql_tgt_conn)

In [50]:
df_source.head(3)

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronic,74988.0,15,TechWorld1,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE

In [51]:
df_target.head(3)

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE

In [52]:
# Identify the extra records where we have additional product_id's in source
fil = ~df_source['product_id'].isin(df_target['product_id'])

In [53]:
df_source[fil]

Empty DataFrame
Columns: [product_id, product_name, category, price, quantity, supplier, product_status]
Index: []

In [56]:
# Compare all the coluns and identify any differences 
assert df_source.equals(df_target),"Data between source and target is not matching"

AssertionError: Data between source and target is not matching

In [65]:
df_source.compare(df_target)

                       product_name                                 category  \
                               self                        other        self
0                               NaN                          NaN  Electronic
7   Noisesksk Cancelling Headphones  Noise Cancelling Headphones         NaN
15             Wireless Chargaaaaer             Wireless Charger         NaN

                   price             supplier
          other     self    other        self      other
0   Electronics  74988.0  74999.0  TechWorld1  TechWorld
7           NaN      NaN      NaN         NaN        NaN
15          NaN      NaN      NaN         NaN        NaN

In [66]:
df_target.compare(df_source)

                   product_name                                      category  \
                           self                            other         self
0                           NaN                              NaN  Electronics
7   Noise Cancelling Headphones  Noisesksk Cancelling Headphones          NaN
15             Wireless Charger             Wireless Chargaaaaer          NaN

                  price            supplier
         other     self    other       self       other
0   Electronic  74999.0  74988.0  TechWorld  TechWorld1
7          NaN      NaN      NaN        NaN         NaN
15         NaN      NaN      NaN        NaN         NaN

In [77]:
# Create a connection string
mysql_tgt_conn = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/aug_2026")
oracle_src_conn = create_engine("oracle+cx_oracle://system:admin@localhost:1521/xe")


# Compare between source ( oracle) and target (mysql) and report test status

query_source = "select * from product"
df_source_oracle = pd.read_sql(query_source,oracle_src_conn)

query_target = "select * from product"
df_target_mysql = pd.read_sql(query_target,mysql_tgt_conn)

In [78]:
assert df_source_oracle.equals(df_target_mysql),"data between source and target does not match"

# rds

In [7]:
mysql_tgt_conn = create_engine("mysql+pymysql://admin:password@mysqldb1.c5ysau0gqsbd.us-east-1.rds.amazonaws.com:3306/sales")

In [8]:
query_target = "select * from product"
df_target_mysql = pd.read_sql(query_target,mysql_tgt_conn)

In [9]:
df_target_mysql

,product_id,product_name,category,price,quantity,supplier,product_status
0,1001,Laptop Pro 14,Electronics,74999.0,15,TechWorld,ACTIVE
1,1002,Wireless Mouse,Electronics,1299.0,80,TechWorld,ACTIVE
2,1003,Mechanical Keyboard,Electronics,3499.0,45,KeyMart,ACTIVE
3,1004,USB-C Hub,Accessories,1899.0,60,ConnectPlus,ACTIVE
4,1005,27 Inch Monitor,Electronics,21999.0,25,VisionTech,ACTIVE
5,1006,Laptop Stand,Accessories,2499.0,35,OfficeGear,ACTIVE
6,1007,Bluetooth Speaker,Audio,2999.0,50,SoundMax,ACTIVE
7,1008,Noise Cancelling Headphones,Audio,8999.0,20,SoundMax,ACTIVE
8,1009,Web Camera,Electronics,4599.0,30,VisionTech,ACTIVE
9,1010,External SSD 1TB,Storage,6999.0,40,DataStore,ACTIVE
10,1011,Portable Hard Drive 2TB,Storage,5899.0,28,DataStore,ACTIVE
11,1012,Power Bank 20000mAh,Accessories,2199.0,55,PowerPlus,ACTIVE
12,1013,Smart Watch,Wearables,4999.0,32,WearTech,ACTIVE
13,1014,Fitness Band,Wearables,2499.0,42,WearTech,ACTIVE
14,1015,Tablet 10 Inch,Electronics,15999.0,18,TechWorld,ACTIVE
15,1016,Wireless Charger,Accessories,1599.0,70,PowerPlus,ACTIVE
16,1017,Office Chair,Furniture,8999.0,12,OfficeGear,ACTIVE
17,1018,Standing Desk,Furniture,18999.0,8,OfficeGear,ACTIVE
18,1019,Laser Printer,Printers,12999.0,14,PrintTech,ACTIVE
19,1020,Inkjet Printer,Printers,7999.0,22,PrintTech,INACTIVE