In [52]:
import pandas as pd

In [51]:
df = pd.read_csv("emp.csv")
df.head()

   eno   ename  salary  deptno         doj   location
0   10   Amber    1000      10   5/14/2018  Bangalore
1    2    Amar    1000      10   3/22/2017  Bangalore
2    8   Sagar    1000      20  11/30/2020  Bangalore
3    4  Thomas    1000      10   8/18/2019  Bangalore
4    5    Jade    2000      10   2/10/2021  Bangalore

# Group by

In [4]:
# Aggregate functions (sum,min,max,count,avg

In [13]:
#Q1 . Count the employees in each department
# expected o/p : deptno,count_employees
# SQL : select deptno,count(deptno) from emp(df) group by deptno

aggr_data = df.groupby('deptno')['eno'].count()
aggr_data

deptno
10    18
20    15
30    14
Name: eno, dtype: int64

In [14]:
type(aggr_data)

pandas.core.series.Series

In [19]:
#convert the series in to dataframe
aggr_data = aggr_data.reset_index()
aggr_data

   index  deptno  eno
0      0      10   18
1      1      20   15
2      2      30   14

In [18]:
type(aggr_data)

pandas.core.frame.DataFrame

In [22]:
#rename eno column in to count_employees
aggr_data.rename(columns={"eno":"count_employees"},inplace=True)

In [23]:
aggr_data

   index  deptno  count_employees
0      0      10               18
1      1      20               15
2      2      30               14

In [35]:
#Q2. get me total count of employees, max salary, min salary,total salary in each department
# SQl: select count(eno) as employees_count,max(salary) as max_salary,min(salary) as min_salary,sum(salary) as total_salary 
# group by deptno

agg_data = df.groupby('deptno')['salary'].agg(['count','max','min','sum'])

In [36]:
type(agg_data)

pandas.core.frame.DataFrame

In [37]:
agg_data

        count    max   min    sum
deptno
10         18   3000  1000  30900
20         15   3200  1000  30000
30         14  41000  1000  68700

In [39]:
#Flatten the data to add indexes
agg_data = agg_data.reset_index()

In [43]:
agg_data.rename(columns={'count':"employee_count",'max':"max_salary","min":"min_salary","sum":"total_salary"},inplace=True)

In [44]:
agg_data

   deptno  employee_count  max_salary  min_salary  total_salary
0      10              18        3000        1000         30900
1      20              15        3200        1000         30000
2      30              14       41000        1000         68700

In [46]:
# Write this summary data in to emp_summary.csv
agg_data.to_csv("emp_summary.csv",index=False)

In [47]:
df

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [53]:
# Updated data set (emp.csv)
df = pd.read_csv("emp.csv")

In [55]:
df.head()

   eno   ename  salary  deptno         doj   location
0   10   Amber    1000      10   5/14/2018  Bangalore
1    2    Amar    1000      10   3/22/2017  Bangalore
2    8   Sagar    1000      20  11/30/2020  Bangalore
3    4  Thomas    1000      10   8/18/2019  Bangalore
4    5    Jade    2000      10   2/10/2021  Bangalore

In [62]:
#Q3. Get me employees count in each location and within each deptno

# expected o/p : 
#location deptno emp_count
#Bangalore 10     2
#Bangalore 20     5
#Chennai   20     5
#Chennai   30     8
# SQL equivalent  : select location,deptno ,count(eno) as emp_count from emp group by location,deptno

data = df.groupby(['location','deptno'])['eno'].count().reset_index()
data.rename(columns = {"eno":"emp_count"},inplace=True)
data

    location  deptno  emp_count
0  Bangalore      10          5
1  Bangalore      20          3
2  Bangalore      30          4
3    Chennai      10          4
4    Chennai      20          3
5    Chennai      30          3
6     Mumbai      10          9
7     Mumbai      20          9
8     Mumbai      30          7

In [83]:
#Q4. Get me total salary in each department and expect for location ="mumbai" and total salary must be 

#SQL : select deptno,sum(salary) as total_sal from emp where location !="mumbai" group by deptno having sum(salary)>50K

filter_location = df['location'] != "Mumbai"
df_filtered = df[filter_location]
df_agg = df_filtered.groupby('deptno')['salary'].sum()
df_agg1 = df_agg.reset_index()

In [84]:
# Way 1
having_fileter = df_agg1['salary'] >50000
df_agg1[having_fileter]

   deptno  salary
2      30   54300

In [90]:
# way2 (Lambda function)
lamda_fil = df_agg.apply(lambda x:x>50000)
df_agg[lamda_fil].reset_index()

   deptno  salary
0      30   54300

# Merge ( SQL Joins)

In [91]:
# inner , outer (left, right, full)

In [107]:
#Q5. Get me employees details along with country
# SQL :  select * from emp as e inner join emp1 as e1 on e.location = e1.location
df1 = pd.read_csv("emp.csv")

In [102]:
df1.head()

   eno   ename  salary  deptno         doj   location
0   10   Amber    1000      10   5/14/2018  Bangalore
1    2    Amar    1000      10   3/22/2017  Bangalore
2    8   Sagar    1000      20  11/30/2020  Bangalore
3    4  Thomas    1000      10   8/18/2019  Bangalore
4    5    Jade    2000      10   2/10/2021  Bangalore

In [108]:
df2 = pd.read_csv("emp1.csv")

In [104]:
df2.head()

    location Country
0  Bangalore   India
1   New York     USA
2  Bangalore   India
3   New York     USA
4  Bangalore   India

In [109]:
data = df1.merge(df2,on='location',how='inner')

In [110]:
data.head(50)

    eno   ename  salary  deptno         doj   location    Country
0    10   Amber    1000      10   5/14/2018  Bangalore      India
1     2    Amar    1000      10   3/22/2017  Bangalore      India
2     8   Sagar    1000      20  11/30/2020  Bangalore      India
3     4  Thomas    1000      10   8/18/2019  Bangalore      India
4     5    Jade    2000      10   2/10/2021  Bangalore      India
5     6   Smith    1000      10   12/1/2016  Bangalore      India
6     7  Robert    3000      20   6/25/2023  Bangalore      India
7     3    Nick    1000      30   9/15/2015  Bangalore      India
8     9   Naman    4000      30   1/20/2020  Bangalore      India
9     1   Vikas    1000      30   10/3/2017  Bangalore      India
10   11  Dennis   41000      30    1/5/2024  Bangalore      India
11   12   Karan    2200      20   6/16/2018  Bangalore      India
12   13  Simran    1500      10  12/19/2019  Singapore  Singapore
13   14    Amit    2000      30    4/9/2022  Singapore  Singapore
14   15    Neha    1700      20   7/22/2021  Singapore  Singapore
15   16   Rahul    1200      10   3/28/2016  Singapore  Singapore
16   17   Divya    3000      30  11/11/2015  Singapore  Singapore
17   18  Rakesh    1800      10    9/4/2020  Singapore  Singapore
18   19  Monica    2500      20    8/7/2023  Singapore  Singapore
19   20    John    2300      30  10/29/2018  Singapore  Singapore
20   21   Sneha    2700      10  12/14/2022  Singapore  Singapore
21   22   David    1000      20   2/17/2017  Singapore  Singapore
22   23   Anita    1500      30   5/21/2019  Singapore  Singapore
23   24   Vinod    1800      10   7/30/2016  Singapore  Singapore
24   25   Meena    2000      20   3/13/2020  Singapore  Singapore