In [1]:
import pandas as pd

# merge ( sql joins)

In [43]:
df_emp = pd.read_csv("data/employees.csv")

In [44]:
df_emp.head()

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50

In [45]:
df_dept = pd.read_csv("data/department.csv")

In [46]:
df_dept.head()

   deptid deptname
0      30   Travel
1      80    Forex
2      10  Finance
3      20       IT

In [47]:
df_sal = pd.read_csv("data/salary.csv")

In [48]:
df_sal

   eno  salary
0    1    1000
1    2    3000
2    3    2000

# inner join

In [12]:
# SQL : select * from empartment as emp inner join department as dept on emp.deptno = dept.deptid

ans_df = df_emp.merge(df_dept,left_on='deptno',right_on='deptid',how='inner')

In [13]:
ans_df

   eno   ename  deptno  deptid deptname
0    1    Ajay      10      10  Finance
1    2   Vijay      20      20       IT
2    3  Mahesh      30      30   Travel

# left join

In [14]:
# SQL : select * from employees as emp left join department as dept on emp.deptno = dept.deptid

ans_df = df_emp.merge(df_dept,left_on='deptno',right_on='deptid',how='left')

In [15]:
ans_df

   eno   ename  deptno  deptid deptname
0    1    Ajay      10    10.0  Finance
1    2   Vijay      20    20.0       IT
2    3  Mahesh      30    30.0   Travel
3    4  Thomas      40     NaN      NaN
4    5  Robert      50     NaN      NaN

# right join

In [17]:
# SQL : select * from employees as emp right join department as dept on emp.deptno = dept.deptid

ans_df = df_emp.merge(df_dept,left_on='deptno',right_on='deptid',how='right')

In [18]:
ans_df

   eno   ename  deptno  deptid deptname
0  1.0    Ajay    10.0      10  Finance
1  2.0   Vijay    20.0      20       IT
2  3.0  Mahesh    30.0      30   Travel
3  NaN     NaN     NaN      80    Forex

In [20]:
# same can be acheved using left join by changing the dataframes sequence
# SQL : select * from department as dept left join employees as emp on emp.deptno = dept.deptid

ans_df = df_dept.merge(df_emp,left_on='deptid',right_on='deptno',how='left')

In [22]:
ans_df

   deptid deptname  eno   ename  deptno
0      10  Finance  1.0    Ajay    10.0
1      20       IT  2.0   Vijay    20.0
2      30   Travel  3.0  Mahesh    30.0
3      80    Forex  NaN     NaN     NaN

# full join

In [25]:
# SQL : select * from employees as emp full join department as dept on emp.deptno = dept.deptid

ans_df = df_emp.merge(df_dept,left_on='deptno',right_on='deptid',how='outer')

In [26]:
ans_df

   eno   ename  deptno  deptid deptname
0  1.0    Ajay    10.0    10.0  Finance
1  2.0   Vijay    20.0    20.0       IT
2  3.0  Mahesh    30.0    30.0   Travel
3  4.0  Thomas    40.0     NaN      NaN
4  5.0  Robert    50.0     NaN      NaN
5  NaN     NaN     NaN    80.0    Forex

# Concat()

In [29]:
# concat() used to concatenate either alongs rows(axis = 0 ) or along columns (axis =1)
# along axis = 0 ( along rows)
#df1(5 rows)
#df2(4 rows)

# along axis = 1 ( along columns)
#df1(5 rows) df2(4 rows)

In [32]:
pd.concat([df_emp,df_dept],axis=0)

   eno   ename  deptno  deptid deptname
0  1.0    Ajay    10.0     NaN      NaN
1  2.0   Vijay    20.0     NaN      NaN
2  3.0  Mahesh    30.0     NaN      NaN
3  4.0  Thomas    40.0     NaN      NaN
4  5.0  Robert    50.0     NaN      NaN
0  NaN     NaN     NaN    10.0  Finance
1  NaN     NaN     NaN    20.0       IT
2  NaN     NaN     NaN    30.0   Travel
3  NaN     NaN     NaN    80.0    Forex

In [39]:
pd.concat([df_emp,df_dept],axis=1)

   eno   ename  deptno  deptid deptname
0    1    Ajay      10    30.0   Travel
1    2   Vijay      20    80.0    Forex
2    3  Mahesh      30    10.0  Finance
3    4  Thomas      40    20.0       IT
4    5  Robert      50     NaN      NaN

In [34]:
pd.concat([df_dept,df_emp],axis=1)

   deptid deptname  eno   ename  deptno
0    10.0  Finance    1    Ajay      10
1    20.0       IT    2   Vijay      20
2    30.0   Travel    3  Mahesh      30
3    80.0    Forex    4  Thomas      40
4     NaN      NaN    5  Robert      50

In [49]:
# Cancate 3 dataframes
pd.concat([df_emp,df_dept,df_sal],axis=1)

   eno   ename  deptno  deptid deptname  eno  salary
0    1    Ajay      10    30.0   Travel  1.0  1000.0
1    2   Vijay      20    80.0    Forex  2.0  3000.0
2    3  Mahesh      30    10.0  Finance  3.0  2000.0
3    4  Thomas      40    20.0       IT  NaN     NaN
4    5  Robert      50     NaN      NaN  NaN     NaN

In [50]:
# Cancate 3 dataframes
pd.concat([df_emp,df_dept,df_sal],axis=0)

   eno   ename  deptno  deptid deptname  salary
0  1.0    Ajay    10.0     NaN      NaN     NaN
1  2.0   Vijay    20.0     NaN      NaN     NaN
2  3.0  Mahesh    30.0     NaN      NaN     NaN
3  4.0  Thomas    40.0     NaN      NaN     NaN
4  5.0  Robert    50.0     NaN      NaN     NaN
0  NaN     NaN     NaN    30.0   Travel     NaN
1  NaN     NaN     NaN    80.0    Forex     NaN
2  NaN     NaN     NaN    10.0  Finance     NaN
3  NaN     NaN     NaN    20.0       IT     NaN
0  1.0     NaN     NaN     NaN      NaN  1000.0
1  2.0     NaN     NaN     NaN      NaN  3000.0
2  3.0     NaN     NaN     NaN      NaN  2000.0

In [58]:
df_emp

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50

In [59]:
df_emp1 = pd.read_csv("data/employees1.csv")

In [60]:
df_emp1

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3   40  Rakesh      70
4   50  Sanjay      60

In [61]:
df_emp

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50

# union and union all

In [62]:
# union all
# SQL : 
#select eno,ename,deptno from emp 
#union all
#select eno,ename,deptno from dept

pd.concat([df_emp,df_emp1])

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3   40  Rakesh      70
4   50  Sanjay      60

In [63]:
# union
# SQL : 
#select eno,ename,deptno from emp 
#union 
#select eno,ename,deptno from dept

pd.concat([df_emp,df_emp1]).drop_duplicates()

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30
3    4  Thomas      40
4    5  Robert      50
3   40  Rakesh      70
4   50  Sanjay      60

# intersection

In [65]:
# intersection
# SQL : 
#select eno,ename,deptno from emp 
#intersect 
#select eno,ename,deptno from dept

df_emp.merge(df_emp1,how='inner')

   eno   ename  deptno
0    1    Ajay      10
1    2   Vijay      20
2    3  Mahesh      30

# read and write data in different file types

In [73]:
df = pd.read_csv("netflix_dataset.csv")
df.count()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
listed_in       8807
description     8807
dtype: int64

In [70]:
df.to_parquet("data/netflix_data.parquet",engine='pyarrow')

In [76]:
df_par = pd.read_parquet("data/netflix_data.parquet")

In [77]:
df_par.count()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
listed_in       8807
description     8807
dtype: int64